### ISSUE TITLE
Flexbox Layout module

### ISSUE THREAD

**Issue by NickToye** [inuitcss/CONTRIBUTING#26]
This is something I was considering adding into my own project, any reason why I shouldn't?

**Comment by csshugs** [comment]
@NickToye 

> any reason why I shouldn't?

**Short answer:** No.

**Long answer:** If you find yourself needing a layout module built with flexbox, go ahead. 
In other words: I use the standard layout module, because a flexbox version would not offer me some enhancement, which would be useful to me, except that you won't need the HTML-comments anymore. But if you need something like layout items which have all the same height (per row), flexbox would be a good choice to achieve this. [I built an extension myself](https://github.com/csshugs/objects.flex-layout) for exact this behaviour.

**Comment by anselmh** [comment]
Marking this as a duplicate of https://github.com/inuitcss/CONTRIBUTING/issues/20.

**Comment by NickToye** [comment]
thanks.
